name: troco_premiado
description: A new Flutter application.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.10
  flutter_mobx: ^1.1.0+2
  mobx: ^1.2.1+4
  flutter_modular: ^2.0.1
  flutter_launcher_icons: ^0.7.5
  json_serializable: ^3.5.0
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  cloud_firestore: ^0.14.0+2
  google_sign_in: ^4.5.3
  dartz: ^0.9.1
  hive_flutter: ^0.3.0+2
  hive: ^1.4.1+1
  path_provider: ^1.6.11
  location: ^3.0.2
  lottie: ^0.7.0+1
  google_fonts: ^1.1.1
  intl: ^0.16.1
  flutter_masked_text: ^0.8.0
  toast: ^0.1.5
  qr_flutter: ^3.2.0

dev_dependencies:
  mockito: ^4.1.3
  modular_codegen: ^2.0.1
  mobx_codegen: ^1.1.2
  build_runner: ^1.10.1
  hive_generator: ^0.8.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


## Slidy Scripts 
vars: 
    clean: flutter clean
    get: flutter pub get
    runner: flutter pub run build_runner
scripts: 
    mobx_build: $runner build
    mobx_watch: $clean & $get & $runner watch
    mobx_build_clean: $clean & $get & $runner build --delete-conflicting-outputs